CREATE OR REPLACE TABLE
  `pdm-funnel-export.Funnel_export_DEPARTMENT_SEO.PDM_DEPARTMENT_SEO_DELIVERABLES_Master` AS
SELECT
  *
FROM
  `Funnel_export_DEPARTMENT_SEO.PDM_DEPARTMENT_SEO_DELIBERABLES`
WHERE
  ClientID IS NOT NULL